### ISSUE TITLE
After you revised the project last time, I tried to run FTT-NAS search. It was normal at first, but after 10epochs were found, an error was reported when running the test() method...

### ISSUE THREAD

**Issue by BaronNashorMan** [walkerning/aw_nas#42]
Hi, helpful author, we meet again...Although I don’t want to follow a questioning method...
The error message is as follows:
![image](https://user-images.githubusercontent.com/40259853/92207910-ace25d80-eebc-11ea-8670-0979d0ca363c.png)
The error seems to stop in your eval_queue method. I compared this method before and after your modification. The method before and after the modification works normally, but this problem occurs after the modification.
If you have time, you can confirm whether this method really has a little problem as I described, thank you very much. 
Maybe this is my own question...

**Comment by walkerning** [comment]
Thanks for you information. Since we have added more codes after the FTT-NAS work, It seems like a bug introduced in our later up modification of the shared component classes (the evaluator, and weights manager). I'll check it as soon as possible.

**Comment by walkerning** [comment]
I have fixed this bug in the latest commit a3834db4eea75ffe4f25b57efb744b0646c69a22.

The bug comes from: (If you are interested): In the early code, we aggregate the rewards/perfs. of each batch by `mean`. Later on, when we are implementing Detection NAS, when implementing mAP reward calculation, this behavior is no longer suitable. Thus, while still keep `mean` as the default, we permit the objective to provide special handling of the aggregate function of batch rewards.

**Comment by BaronNashorMan** [comment]
Thank you for your careful hints and explanations. I will continue to run the code according to your instructions. Thank you very much and wish you all the best.
