### ISSUE TITLE
ray version

### ISSUE THREAD

**Issue by LiuJia68** [walkerning/aw_nas#44]
Could I know the ray version?

**Comment by walkerning** [comment]
Hello, it has been a long time since I last use the ray dispatcher in async trainer, or something like the script (https://github.com/walkerning/aw_nas/blob/master/scripts/ray_pipeline.py) to run multiple experiments only (in which case `ray` just help assign GPU ids).  For your information, when I uses these functionalities, I use ray 0.6.6. However, I'm not sure whether ray dispatcher will work in the current version.

If you are interested in help aw_nas development, or discuss more about your use case of aw_nas, feel free to contact me by email too!
