### ISSUE TITLE
Similar DAG encoding scheme to an existing paper

### ISSUE THREAD

**Issue by muhanzhang** [walkerning/aw_nas#49]
Hi! The presented DAG encoding scheme is very similar to the asynchronous message passing proposed in our existing paper "D-VAE: A Variational Autoencoder for Directed Acyclic Graphs", published in NeurIPS-2019. Unfortunately, it is not cited or discussed. Could you have a check?

Best,
Muhan

**Comment by walkerning** [comment]
Hi, sorry for the late reply. I'm busy with my thesis lately. I have checked your paper. Indeed, the design of the encoder is similar. Since my background is only NAS (which might be obvious from the immature descriptions on GCNs in the paper), I did not find your paper after a lot of search when doing the GATES work. We will modify our arXiv version to cite it.
